<?php

$wc_latlong = array(
    'wc_lat' => variable_get('wc_latitude', '10.8'),
    'wc_long' => variable_get('wc_longitude', '78.7'),
    'wc_disp' => explode(';',variable_get('wc_Disp_Info','1;1;1;0;0;0;0;0;0;0;0;')),
);

drupal_add_js(array('wc_latlong' => $wc_latlong), 'setting');
drupal_add_js('http://maps.google.com/maps/api/js?sensor=false','external');
drupal_add_js(drupal_get_path('module', 'weathercheck').'/js/AdminMap.js');

function weathercheck_block_info() {
    $blocks['weather'] = array(
    'info' => t('Weather Check'),
    );
    return $blocks;
}

function weathercheck_block_view($delta = '') {
    $block = array();
    switch ($delta) {
    case 'weather':
        $path = drupal_get_path('module', 'weathercheck');
        $block['subject'] = t('Weather Check');
        $block['content'] = array(
            '#theme' => 'weather_status',
            '#attached' => array(
                'js' => array(
                'https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js',
                $path . '/js/weathercheck.js',
                ),
            ),
        );
        break;
    }
    return $block;
}

function weathercheck_theme() {
    return array(
    'weather_status' => array(
        'template' => 'weather-status',
        'variables' => array(),
        ),
    );
}

function weathercheck_menu() {
    $menu['admin/config/weathercheck'] = array( 
        'title' => t('Weather Check'),
	'description' => t('Weather Check tools'), 
	'access arguments' => array('access administration pages'), 
	'position' => 'right', 
    );   
 
    $menu['admin/config/weathercheck/config'] = array( 
	'title' => t('Weather check configuration') , 
	'description' => t('Configure the weather check module') , 
	'page callback' => 'drupal_get_form',
	'page arguments' => array('weathercheck_form'),
	'type' => MENU_NORMAL_ITEM, 
	'access arguments' => array('administer site configuration'), 
    );   
    
    return $menu;
}

function weathercheck_form($form, &$form_state) {	
    $form['wc_latitude'] = array(
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_number'),
        '#title' => t('Latitude of desired location'),
        '#required' => TRUE,
        '#default_value' => variable_get('wc_latitude', '10.8'),
        '#prefix' => "
        <div>
            <p>Enter the details of the default desired location for your weather map.</p>
        </div>
        <div id='AdminMap' style='height: 120px; width: 500px; posotion:relative; float: right;'></div>
        ",
    );
  
    $form['wc_longitude'] = array(
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_number'),
        '#title' => t('Longitude of desired location'),
        '#required' => TRUE,
        '#default_value' => variable_get('wc_longitude', '78.7'),
    );

    $options = array();
    $options[1]["1"] = "City Name";
    $options[1]["2"] = "Country Code";
    $options[1]["3"] = "Temperature";
    $options[1]["4"] = "Minimum temperature";
    $options[1]["5"] = "Maximum temperature";
    $options[1]["6"] = "Cloud Description";
    $options[1]["7"] = "Pressure";
    $options[1]["8"] = "Humidity";
    $options[1]["9"] = "Visibility level";
    $options[1]["10"] = "Wind speed";
    $options[1]["11"] = "Wind degree";

    $form['wc_Disp_Select'] = array(
        '#title' => t(''),
        '#type' => 'checkboxes',
        '#description' => t(''),
        '#options' => $options[1],
        '#prefix' => '<hr/><br/>Select all the required details for weather forecast:',
        '#default_value' => (isset($conf['wc_Disp_Select'])?variable_get('wc_Disp_Select'):array("1","2","3")),
    ); 

    $form['update'] = array(
        '#type' => 'button',
        '#value' => 'Update',
        '#ajax' => array(
        'callback' => 'weathercheck_form_callback',
        'wrapper' => 'update-name-value',
        ),
    );
  
    $form['wc_Disp_Info'] = array(
        '#type' => 'hidden',
        '#value' => (
        (empty($form_state['values']['wc_Disp_Select'][1])?'0;':'1;').
        (empty($form_state['values']['wc_Disp_Select'][2])?'0;':'1;').
        (empty($form_state['values']['wc_Disp_Select'][3])?'0;':'1;').
        (empty($form_state['values']['wc_Disp_Select'][4])?'0;':'1;').
        (empty($form_state['values']['wc_Disp_Select'][5])?'0;':'1;').
        (empty($form_state['values']['wc_Disp_Select'][6])?'0;':'1;').
        (empty($form_state['values']['wc_Disp_Select'][7])?'0;':'1;').
        (empty($form_state['values']['wc_Disp_Select'][8])?'0;':'1;').
        (empty($form_state['values']['wc_Disp_Select'][9])?'0;':'1;').
        (empty($form_state['values']['wc_Disp_Select'][10])?'0;':'1;').
        (empty($form_state['values']['wc_Disp_Select'][11])?'0;':'1;')
        ),
        '#prefix' => "<div id='update-name-value'>",
        '#suffix' => "</div>",
    );
    return system_settings_form($form);
}

function weathercheck_form_callback($form, $form_state) {
    return $form['wc_Disp_Info'];
}
